# Generated by Django 4.1.7 on 2023-03-09 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_flat', models.CharField(max_length=1999)),
                ('price_flat', models.FloatField(verbose_name=5.0)),
                ('pub_date', models.DateTimeField(verbose_name='date publish')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_house', models.CharField(max_length=2000)),
                ('price_house', models.FloatField(verbose_name=10.0)),
                ('pub_date', models.DateTimeField(verbose_name='date publish')),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_land', models.CharField(max_length=1000)),
                ('price_land', models.FloatField(verbose_name=1.0)),
                ('pub_date', models.DateTimeField(verbose_name='date publish')),
            ],
        ),
        migrations.CreateModel(
            name='NewConstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_new_construction', models.CharField(max_length=1998)),
                ('price_new_construction', models.FloatField(verbose_name=5.0)),
                ('pub_date', models.DateTimeField(verbose_name='date publish')),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_cities', models.CharField(max_length=2000)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.flat')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.house')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.land')),
                ('new_construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='www.newconstruction')),
            ],
        ),
    ]
